LIST: [PATCH] rust: alloc: allow different error types in `KBox::pin_slice`
Previously, `KBox::pin_slice` required the initializer error type to match
the return error type via `E: From<AllocError>`. This prevented using
infallible initializers like `new_mutex!` inside `pin_slice`, because
`Infallible` does not implement `From<AllocError>`.

Introduce a separate type parameter `E2` for the initializer error type and
require `AllocError: Into<E>` and `E2: Into<E>` instead. This allows the
initializer to return a different error type that can be converted into the
final error type, enabling use of infallible pin initializers in fallible
allocation contexts.

Link: https://msgid.link/20260214-pin-slice-init-v1-1-0b174fbb1844@kernel.org
Signed-off-by: Andreas Hindborg <a.hindborg@kernel.org>